title: Project Shiba Wiki
description: Welcome to our server documentation!
theme: just-the-docs
color_scheme: dark
nav_external_links_new_tab: true
permalink: /:title
url: https://just-the-docs.github.io

aux_links:
  Discord: https://discord.gg/projectshiba
  Website: https://projectshiba.com

nav_external_links:
  - title: Discord
    url: https://discord.gg/projectshiba
  - title: Website
    url: https://projectshiba.com

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/

search_enabled: true
search:
  rel_url: false

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html